### PR TITLE
Fix `to_quimb_tensor()`

### PR DESCRIPTION
**Pull request by y-richie-y**
Support phased spiders with more than 1 leg, fulfilling the condition stated in https://github.com/Quantomatic/pyzx/blob/e93a0829ef467bd6c9887332b4899e0f7c1ddc80/pyzx/quimb.py#L50

Example code
```python
from pyzx import Circuit
from pyzx.circuit.gates import Z, NOT
from pyzx.quimb import to_quimb_tensor

c = Circuit(1)
c.add_gate(Z(0))
c.add_gate(NOT(0))

g = c.to_graph()
inds = [str(i) for i in [*g.inputs(), *g.outputs()]]
print(to_quimb_tensor(g).contract(output_inds=inds).data)
```

### CODE REVIEW

**Comment by y-richie-y** [comment]
`to_gh()` acts in-place, and the graph already gets copied within `to_quimb_tensor()`. Would you still prefer me to change it to copy it within `unfuse_phase_spiders()`?

**Comment by jvdwetering** [comment]
Oh I missed that. Never mind then.

**Comment by tlaakkonen** [comment]
I'm not sure this fix is necessary - the condition in the comment doesn't have anything to do with what kind of spiders are allowed to have phases. The phase tensors are *extra* spiders added to represent the phases (essentially doing exactly the unfusing you are doing). The original spiders are all converted into hyper-indices, no tensors are ever created for individual spiders. This rewrite just adds an unnecessary identity tensor that quimb will remove anyway when you do a diagonal_reduce simplification pass.

**Comment by y-richie-y** [comment]
Yeah not sure why it didn't work for me in the first place. We can roll back this commit.

**Pull request merged**
