### PR TITLE
Add support for most OpenQASM 2 and 3 standard gates.

### LINKED ISSUE #153: cp gate support for QASMParser
Hi @jvdwetering, I faced the problem of phase(p), and controlled phase(cp) gate when parsing the qasm string. I thought I might try working on this issue to add p and cp gate support. Your guidance and input would be greatly appreciated.

### PR DESCRIPTION
**Pull request by dlyongemallo**
Adds support for the most common OpenQASM 2 and 3 standard library gates, and a unit test to ensure that the implementations in pyzx and qiskit are the same up to a global phase.

This PR fixes #153 and #158, adds tests to verify #102 and #103, and should now go most of the way towards completing #87 and #116.

### CODE REVIEW

**Comment by dlyongemallo** [comment]
@jvdwetering I'm slightly unsure about whether `to_basic_gates()` for `crx` and `rxx` are correct. Does the list which is returned have to consist only of gates for which `to_basic_gates()` return themselves, or is `to_basic_gates()` defined recursively?

**Comment by dlyongemallo** [comment]
There are a few outstanding gates in `qelib1.inc` and `stdgates.inc` which haven't been included. I wanted to make sure that these are correct first, before I implement those.

**Comment by jvdwetering** [comment]
to_basic_gates should itself return a list of basic gates, so it should not have to be called recursively.

**Comment by jvdwetering** [comment]
I've never seen anyone use those gates, so I think it's fine if these are not implemented for now.

**Comment by jvdwetering** [comment]
Can this be merged?

**Comment by dlyongemallo** [comment]
AFAIK, yes. Unless you have any comments or requests about the code.

**Comment by dlyongemallo** [comment]
p.s. I just want to thank @jakelishman for his guidance in explaining the difference between how OpenQASM 2 and 3 represents the gates, which made this PR possible.

**Pull request merged**
