### PR TITLE
Add more symbolic functionality

### PR DESCRIPTION
**Pull request by y-richie-y**
From my experimentation this enables `full_reduce` on symbolic diagrams. Here is an example on a DisCoCat diagram:

image
image

### CODE REVIEW

**Comment by y-richie-y** [comment]
Hm is this a bug I just introduced?
image
image

I don't see how phases `START__s_2` and `test__s.r@s_0/2` can be made adjacent.

**Comment by jvdwetering** [comment]
Yeah it looks like something weird is going on. Can you try the same diagram, but replacing each parameter by some non-canonical non-Clifford phase, to see if the same thing happens?

**Comment by jvdwetering** [comment]
Then you can also directly evaluate the matrices to see if it is actually a bug

**Comment by y-richie-y** [comment]
still happens, seems unrelated to the PR
image
image


They appear to be equal!

```
array([[ 0.50073846+0.00004646j,  0.50073846+0.00004646j,
         0.49704253+0.0470077j ,  0.49704253+0.0470077j ,
         0.49827673+0.03132563j,  0.49827673+0.03132563j,
        -0.4945808 -0.07828686j, -0.4945808 -0.07828686j],
       [ 0.49926045-0.00002324j, -0.49926045+0.00002324j,
         0.49852053+0.0470774j , -0.49852053-0.0470774j ,
         0.50073846+0.00004646j, -0.50073846-0.00004646j,
        -0.49704253-0.0470077j ,  0.49704253+0.0470077j ]])
```

**Comment by y-richie-y** [comment]
Do you understand this? @jvdwetering

**Comment by jvdwetering** [comment]
Are you sure this is not a case of spiders appearing to be on top of each other in the drawing? Are they actually connected?

**Comment by y-richie-y** [comment]
I'm dragging them, they appear to be connected. Let me try to produce a minimal example.

**Comment by jvdwetering** [comment]
I think this must be the result of a boundary pivot on the spider connected to the second input and the hub part of the phase gadget.

**Comment by y-richie-y** [comment]
Just to confirm, so we think there is no bug right?

**Comment by jvdwetering** [comment]
Well, if the matrix is preserved, then it is a correct rewrite.

**Comment by y-richie-y** [comment]
Ok. The first change I believe is correct, as it appears to be checking if the spider is Clifford.
```
if phases[v] != 0 and hasattr(phases[v], 'denominator') and phases[v].denominator > 2 and len(list(g.neighbors(v)))==1:
```

In the second change, it is looking for phase gadgets, so is it the case that we want to **include** non-clifford phases, and also is it something that would work anyway if we didn't match it?

**Comment by y-richie-y** [comment]
@jvdwetering do you think this is good to merge?

**Comment by jvdwetering** [comment]
From what I saw in your changes this all looks fine. But aren't there more rewrite rules you need to change to make them compatible with symbolic angles?

**Comment by y-richie-y** [comment]
I'll have another look tomorrow, but full_reduce has been working for me in the wild.

**Pull request merged**
